service: lambda-layer

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer: 
      name: python-ml-layer
      description: "Layer which contains numpy, tendorflow library"
      compatibleRuntimes:
        - python3.8
